### ISSUE TITLE
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by skgusrb12** [1ytic/warp-rnnt#20]
![스크린샷, 2021-07-15 10-53-19](https://user-images.githubusercontent.com/51149957/125717972-ed3d8d1d-e49c-4c7a-8566-e3be83ac970a.png){: width="50%" height="50%"}

Does the repo not support CUDA 11.x?

* My environment:
- GPU : GeForce RTX 3090ti
- Pytorch 1.9.0 (cuda : 11.1)

**Comment by 1ytic** [comment]
Make sure you compiled the package with cuda 11.

**Comment by mathshangw** [comment]
excuse me did you solve it ?

**Comment by mathshangw** [comment]
> Make sure you compiled the package with cuda 11.

how can i check that , please ?
