### ISSUE TITLE
question about the gather arguments

### ISSUE THREAD

**Issue by wl-junlin** [1ytic/warp-rnnt#25]
> core_gather.cu is a memory-efficient version that expects log_probs with the shape (N, T, U, 2) only for blank and labels values. It shows excellent performance with a large vocabulary.

Hello, what dose the gather mean? Or when should I set gather to True? Does the log_probs shape (N, T, U, 2) means only have two classes, blank and whatever labels?

**Comment by 1ytic** [comment]
This flag decreases the memory allocation for the array of gradients. You can look at the [implementation](https://github.com/1ytic/warp-rnnt/blob/2944982ba1a53f6d20ba74c14b72cdd32e335d56/pytorch_binding/warp_rnnt/__init__.py#L73). For example, if you have a large output vocabulary `V`, I highly recommend using this flag.
