### ISSUE TITLE
Not support Pytorch 1.5

### ISSUE THREAD

**Issue by li563042811** [1ytic/warp-rnnt#8]
I used warp_rnnt 0.4.0 and tried 0.3.0. Both of them could not work with pytorch 1.5. 
The traceback showed this:

_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1012CUDATensorIdEv

But when I changed pytorch from 1.5 to 1.0. Both of them worked.
Here is my env:
python   3.7.7
pytorch  1.5
gcc         4.8.5 

Maybe you can fix it and your work will be appreciated.

**Comment by 1ytic** [comment]
You probably need to install a proper CUDA libraries. Have a look at this issue #7
